config/routes.rb
Rails.application.routes.draw do

  scope '/admin' do
    resources :categories, :tags, :products, :years, :brands, :carts, :charges

    resources :line_items do
      put 'decrease', on: :member
      put 'increase', on: :member
    end
  end

  devise_for :users

  root 'front#index'
  get 'products/:id', to: 'front#show_product', as: :show_product

  get "admin", to: 'admin#charts'

  get "admin/users/defaults-users" => 'admin#n_users', as: :n_users
  get "admin/users/admins-users" => 'admin#a_users', as: :a_users

  get "admin/user/new" => 'admin#new_user', as: :new_user
  post "admin/user" => 'admin#create_user'

  get "admin/user/:id" => 'admin#show_user', as: :admin_show_user

  get "admin/user/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/user/:id" => 'admin#destroy_user', as: :user_delete
  
  patch "admin/user/:id" => 'admin#update'
  put "admin/user/:id" => 'admin#update', as: :user_edit_s

  get 'tags/:tag', to: 'front#index', as: :tag_search

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	validates :name, uniqueness: true, presence: true
	has_many :taggings
	has_many :products, through: :taggings
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @body_class = 'admin'
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @body_class = 'admin'

  end

  # GET /tags/new
  def new
    @body_class = 'admin'

    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
    @body_class = 'admin'
    
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, 'nombre' %>
    <%= f.text_field :name, required: true %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<%= render 'admin/nav' %>

<div class="container">

	<h1>Editing Tag</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @tag %> |
	<%= link_to 'Back', tags_path %>
</div>

app/views/tags/index.html.erb
<%= render 'admin/nav' %>

<div class="container">

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>
</div>

app/views/tags/new.html.erb
<%= render 'admin/nav' %>

<div class="container">


	<h1>New Tag</h1>

	<%= render 'form' %>

	<%= link_to 'Back', tags_path %>
</div>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>
<%= @tag.name %>	
<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>