config/routes.rb
Rails.application.routes.draw do

  scope '/admin' do
    resources :categories, :tags, :products, :years, :brands, :carts, :charges

    resources :line_items do
      put 'decrease', on: :member
      put 'increase', on: :member
    end
  end

  devise_for :users

  root 'front#index'
  get 'products/:id', to: 'front#show_product', as: :show_product

  get "admin", to: 'admin#charts'

  get "admin/users/defaults-users" => 'admin#n_users', as: :n_users
  get "admin/users/admins-users" => 'admin#a_users', as: :a_users

  get "admin/user/new" => 'admin#new_user', as: :new_user
  post "admin/user" => 'admin#create_user'

  get "admin/user/:id" => 'admin#show_user', as: :admin_show_user

  get "admin/user/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/user/:id" => 'admin#destroy_user', as: :user_delete
  
  patch "admin/user/:id" => 'admin#update'
  put "admin/user/:id" => 'admin#update', as: :user_edit_s

  get 'tags/:tag', to: 'front#index', as: :tag_search

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :brand

  has_many :taggings
  has_many :tags, through: :taggings

  
  # has_many :likes, dependent: :destroy
  
  # has_many :pictures, dependent: :destroy
  # accepts_nested_attributes_for :pictures

  has_many :line_items
  has_many :charges, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item


  validates :title, length: { maximum: 50, too_long: "%{count} letras son las maximas permitidas!" }, uniqueness: true, presence: true
  validates :sku, length: { in: 7..15, too_long: "%{count} caracteres son las maximas permitidas!", too_short: "%{count} caracteres son los minimos permitidos " }, uniqueness: true, presence: true 
  validates :price, numericality: {greater_than_or_equal_to: 2.00}
  validates :cost_price, numericality: {greater_than_or_equal_to: 1.00}
  validates :content, length: { maximum: 250, too_long: "%{count} letras son las maximas permitidas!" }, presence: true 

  scope :default_admin, -> {order('created_at desc')}
  scope :default, -> {order('published_at desc').where("published_at <= ?", DateTime.now)}

  scope :published, -> {default.includes(:tags).where(published: true)} 
  scope :featured, -> {published.where(featured: true).limit(16)}
  scope :recent, -> {published.limit(8)} 
  # scope :popular, -> {published.where('likes_count > 5').order('likes_count desc').limit(9)}


  def self.tagged_with(name)
    Tag.find_by_name!(name).products
  end


  def self.tag_counts
    #returns the most used tags

    Tag.select("tags.id, tags.name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id, tags.id, tags.name").order("count desc").limit(8)
  end


  def tag_list
    #esto retorna un string
    tags.collect(&:name).join(", ")
  end

  def tag_list=(names)
    # self.tags = names.downcase.split(",").map do |n|
    #   Tag.where(name: n.strip).first_or_create!
    # end
    # names.collect do |n|
    #   self.tags << n
    # end

    # names.each do |t|
    #   if t = Tag.find_by_name(name: t)
    #     self.tags << t
    #   end
    # end

    # self.tags << names

    # self.tag_ids = Tag.where(name: names).pluck(:id)

    # names.map {|name| self.tags.find_or_initialize_by(name: name)}
  end

  def to_param
    "#{id}-#{title.parameterize}"
  end

  private
    #ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # before_filter :check_super

  # GET /products
  # GET /products.json
  def index
    @body_class = 'admin'
    @products = Product.default_admin

    @st = Product.ransack(params[:q])
    @products = @st.result(distinct: true).default_admin.paginate(per_page: 50, page: params[:page])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @body_class = 'admin'
  end

  # GET /products/new
  def new
    @body_class = 'admin'
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @body_class = 'admin'
  end

  # POST /products
  # POST /products.json
  def create
    # @product = Product.new(product_params)

    @product = current_user.products.new(product_params)

    # if params[:product][:tags]
    #   puts "true sdfksjdfhkjsdhkjsdfh"
    # end
    # @product << product_params[:tags]


    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    puts "-" * 50
    puts params[:product][:card_number] + "\n \n \n"
    puts "-" * 50

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :content, :published, :published_at, :sku, :weight, :price, :cost_price, :featured, :stock, :category_id, :ancho, :perfil, :rin, :tire_brand, :tire_model_brand, :performance_km, :performance_cold, :performance_dry, :performance_wet, :brand_id, tag_ids: [], year_ids: [] )
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="text-area-content">

    <%= render 'shared/text_editor' %>
    <%= f.text_area :content, placeholder: "contenido", id: "textarea" %>
  </div>










  <div class="field">
    <%= f.check_box :published %>
    <%= f.label :published, "publicado?" %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.date_field :published_at, class: "datepicker" %>
  </div>
  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :cost_price %><br>
    <%= f.text_field :cost_price %>
  </div>
  <div class="field">
    <%= f.check_box :featured %>
    <%= f.label :featured, "Descatado?" %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :ancho %><br>
    <%= f.number_field :ancho %>
  </div>
  <div class="field">
    <%= f.label :perfil %><br>
    <%= f.number_field :perfil %>
  </div>
  <div class="field">
    <%= f.label :rin %><br>
    <%= f.number_field :rin %>
  </div>
  <div class="field">
    <%= f.label :tire_model_brand, "nombre modelo" %>
    <%= f.text_field :tire_model_brand %>
  </div>
  <div class="field">
    <%= f.label :performance_km %><br>
    <%= f.number_field :performance_km %>
  </div>
  <div class="field">
    <%= f.label :performance_cold %><br>
    <%= f.number_field :performance_cold %>
  </div>
  <div class="field">
    <%= f.label :performance_dry %><br>
    <%= f.number_field :performance_dry %>
  </div>
  <div class="field">
    <%= f.label :performance_wet %><br>
    <%= f.number_field :performance_wet %>
  </div>

 

  <p>
    <%= f.label :tag_ids, "tags" %>
    <%= f.select :tag_ids, Tag.all.collect {|x| [x.name, x.id] }, 
                                        {}, 
                                        { multiple: true, class: "chosen-select"} %>
  </p>

  <div class="field">
    <%= f.label :brand, "Marca" %><br>
    <%= f.collection_select(:brand_id, Brand.all, :id, :name, {include_blank: true}) %>
  </div>
  
  <div class="field">
    <%= f.label :category, "Categoria" %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :name, { include_blank: true}) %>
  </div>


  <input class="radius" type="text" name="product[card_number]" data-conekta="card[number]" placeholder="Numero de tarjeta de crédito">

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script type="text/javascript">
  var editor = new wysihtml5.Editor("textarea", {
    toolbar:        "toolbar",
    parserRules:    wysihtml5ParserRules
  });
</script>

app/views/products/edit.html.erb
<%= render 'admin/nav' %>

<div class="container">
	<h1>Editing Product</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>

</div>

app/views/products/index.html.erb
<%= render 'admin/nav' %>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <a href="<%= new_product_path %>" class="btn-floating btn-large waves-effect waves-light red tooltipped" data-position="left" data-tooltip="Producto nuevo"><i class="mdi-content-add"></i></a>

</div>

  <div class="search-div red lighten-4 row">
    <div class="col s9">
      <input type="text" class="" placeholder="busqueda" >
    </div>
    <div class="col s3">
      <a href="<%= root_path %>" class="mdi-action-search btn"><i class=""></i></a>
      <a href="<%= root_path %>" class="mdi-action-settings btn"><i class=""></i></a>
    </div>
  </div>

    <div class="container">

      <div class=" row">


        <h5 class="center-align white-text">Busqueda</h5>
          <%= search_form_for(@st, html:{class: ""}) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :title_or_sku_cont, class: "validate" %>
                <label>palabras</label>
                
              </div>
              <div class="input-field col s2">
                <%= f.collection_select(:category_id_eq, Category.all, :id, :name, {include_blank: true}) %>
                <label>categoria</label>
              </div>
              <div class="input-field col s2">
                <%= f.text_field :price_eq, class: "validate" %>
                <label>precio</label>
              </div>
              <div class="input-field col s2">
                <%= f.text_field :weight_eq, class: "validate" %>
                <label>peso</label>
              </div>
           
              <div class="input-field col s2">
                <%= f.collection_select :brand_id_eq, Brand.all, :id, :name, {include_blank: true} %>
                <label>marca</label>
              </div>
              <div class="input-field col s2">
                <%= f.number_field :ancho_eq, class: "validate" %>
                <label>ancho</label>
              </div>
              <div class="input-field col s2">
                <%= f.number_field :perfil_eq, class: "validate" %>
                <label>perfil</label>
              </div>
              <div class="input-field col s2">
                <%= f.number_field :rin_eq, class: "validate" %>
                <label>rin</label>
              </div>
              <div class="col s2">
                <%= f.check_box :published_true, checked: true %>
                <%= f.label :published_true, "publicado" %>
              </div>
               
            </div>
              <%= f.button "Busqueda", class: "btn" %>
              <%= link_to "restablecer", products_path, class: "btn-flat white-text" %>
          <% end %>

      </div>
      
      <table class="bordered centered">
        <thead>
          <tr>
            <th data-field="sku">Sku</th>
            <th><%= sort_link(@st, :stock) %></th>
            <th>titulo</th>
            <th><%= sort_link(@st, :published, "publicado?") %></th>
            <th><%= sort_link @st, :price, "precio" %></th>
            <th><%= sort_link @st, :category, "categoria" %></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr class="">
              <td><%= product.sku %></td>
              <td><%= product.stock %></td>
              <td><%= product.title %></td>
              <td><%= product.published %></td>
              <td><%= product.price %></td>
              <td><%= product.category.name %></td>
              <td><%= link_to 'Show', product_path(product) %></td>
              <td><%= link_to 'Edit', edit_product_path(product) %></td>
              <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= will_paginate @products, page_links: true, class: "text-center will-paginate" %>


    </div>

app/views/products/new.html.erb
<%= render 'admin/nav' %>

<div class="container">

	<%= link_to 'Back', products_path %>
	<h1>New Product</h1>

	<%= render 'form' %>

</div>

app/views/products/show.html.erb
<%= render 'admin/nav' %>

<div class="container">
<% if @product.user %>
  <p>
    <strong>User:</strong>
    <%= @product.user.name %>
  </p>
<% end %>

  <p>
    <strong>Title:</strong>
    <%= @product.title %>
  </p>


  <p>
    <strong>Content:</strong>
    <%= sanitize @product.content %>
  </p>

  <p>
    <strong>Published:</strong>
    <%= @product.published %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= local_time @product.created_at %>
  </p>
  <p>
    <strong>Published at:</strong>
    <%= local_time @product.published_at %>
  </p>

  <p>
    <strong>Sku:</strong>
    <%= @product.sku %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= @product.weight %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>

  <p>
    <strong>Cost price:</strong>
    <%= @product.cost_price %>
  </p>

  <p>
    <strong>Featured:</strong>
    <%= @product.featured %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= @product.stock %>
  </p>

  <p>
    <strong>Likes count:</strong>
    <%= @product.likes_count %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= @product.brand.name %>
  </p>


  <p>
    <strong>Category:</strong>
    <%= @product.category.name %>
  </p>

  <p>
    <b>tags:</b>
    <% @product.tags.each do |t| %>
      <%= t.name %>
    <% end %>
  </p>

 

  <%= link_to 'atras', :back %>

</div>