config/routes.rb
Rails.application.routes.draw do

  scope '/admin' do
    resources :categories, :tags, :products, :years, :brands, :carts, :charges

    resources :line_items do
      put 'decrease', on: :member
      put 'increase', on: :member
    end
  end

  devise_for :users

  root 'front#index'
  get 'products/:id', to: 'front#show_product', as: :show_product

  get "admin", to: 'admin#charts'

  get "admin/users/defaults-users" => 'admin#n_users', as: :n_users
  get "admin/users/admins-users" => 'admin#a_users', as: :a_users

  get "admin/user/new" => 'admin#new_user', as: :new_user
  post "admin/user" => 'admin#create_user'

  get "admin/user/:id" => 'admin#show_user', as: :admin_show_user

  get "admin/user/:id/edit" => 'admin#edit', as: :user_edit
  delete "admin/user/:id" => 'admin#destroy_user', as: :user_delete
  
  patch "admin/user/:id" => 'admin#update'
  put "admin/user/:id" => 'admin#update', as: :user_edit_s

  get 'tags/:tag', to: 'front#index', as: :tag_search

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
  belongs_to :charge

  def total_price_line
  	price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create, :decrease, :destroy, :increase]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    # @line_item = LineItem.new(line_item_params)

    product = Product.find(params[:product_id])
    quantity = params[:line_item][:quantity]

    case product.category.name
    when "llanta"
      @line_item = @cart.add_product(product.id, product.price, quantity)
    else
      @line_item = @cart.add_product(product.id, product.price, quantity)
    end


    respond_to do |format|
      if @line_item.save
        format.html { redirect_to show_product_path(product), notice: 'Producto añadido al carrito...' }
        # format.json { render :show, status: :created, location: @line_item }
        format.js { @current_item = @line_item }

      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to root_path, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def increase
    item = LineItem.find(params[:id])

    @line_item = @cart.add_pp(item)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to cart_charges_path, notice: 'itemmmmm updated!'}
        format.js { @current_item = @line_item }
      else
        format.html { render action: "new" }
      end
    end
  end
  def decrease
    product = LineItem.find(params[:id])
  
    @line_item = @cart.decrease(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to cart_charges_path, notice: 'itemmmmm updated!'}
        format.js { @current_item = @line_item }
      else
        format.html { render action: "edit" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:cart_id, :quantity, :price, :post_id, :charge_id, :property)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :charge_id %><br>
    <%= f.text_field :charge_id %>
  </div>
  <div class="field">
    <%= f.label :property %><br>
    <%= f.text_field :property %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if @cart.line_items.empty? %>
	<div id="cart">
		Carrito vacio
	</div>
<% else %>
	<div id="cart">
		<table>
			<thead>
				<th>ITEM</th>
				<th></th>
				<th>PRECIO</th>
				<th></th>
			</thead>
			<tbody>
				<% @cart.line_items.each do |item| %>
					<tr>
						<td>x<%= item.quantity %></td>
						<td><%= item.post.title %></td>
						
						<td>$ <%= item.total_price_line %></td>
						<td><%= link_to "x", item, method: :delete, data: {confirm: "Estas seguro?"}, remote: true %></td>
					</tr>
				<% end %>

			</tbody>
			<tfoot>
				<tr class="total_line">
					<td></td>
					<td class="total">TOTAL </td>
					<td class="total_cell"> $<%= @cart.total_price_cart %></td>
				</tr>
			</tfoot>

		</table>
			<%= link_to 'Ir a carrito', cart_charges_path, class: "button green small radius expand" %>
			<%= link_to 'Vaciar carrito', @cart, method: :delete, data: {confirm: 'Estas seguro?'}, remote: true, class: "button red tiny radius expand" %>
	</div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Price</th>
      <th>Product</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.quantity %></td>
        <td><%= line_item.price %></td>
        <td><%= line_item.product.title %></td>
        <td><%= line_item.property %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @line_item.price %>
</p>

<p>
  <strong>Post:</strong>
  <%= @line_item.post %>
</p>

<p>
  <strong>Charge:</strong>
  <%= @line_item.charge %>
</p>

<p>
  <strong>Property:</strong>
  <%= @line_item.property %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>